# Generated by Django 4.2.23 on 2025-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the article', null=True, upload_to='articles/'),
        ),
    ]
