# Generated by Django 4.2.23 on 2025-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', help_text='Article language', max_length=2),
        ),
    ]
