# Generated by Django 4.2.23 on 2025-11-10 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('movie_title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField(help_text='Review content (HTML supported)')),
                ('poster_image', models.ImageField(help_text='Movie poster image', upload_to='movie_reviews/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('watch_link', models.URLField(blank=True, help_text='Link to watch the movie')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to='accounts.author')),
            ],
            options={
                'verbose_name': 'Movie Review',
                'verbose_name_plural': 'Movie Reviews',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='reviews_mov_publish_48f339_idx'), models.Index(fields=['slug'], name='reviews_mov_slug_320275_idx'), models.Index(fields=['rating'], name='reviews_mov_rating_ace126_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(blank=True, max_length=20)),
                ('book_year', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField(help_text='Review content (HTML supported)')),
                ('cover_image', models.ImageField(help_text='Book cover image', upload_to='book_reviews/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('purchase_link', models.URLField(blank=True, help_text='Link to purchase the book')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='accounts.author')),
            ],
            options={
                'verbose_name': 'Book Review',
                'verbose_name_plural': 'Book Reviews',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='reviews_boo_publish_23ac26_idx'), models.Index(fields=['slug'], name='reviews_boo_slug_c8fcab_idx'), models.Index(fields=['rating'], name='reviews_boo_rating_c9ba3e_idx')],
            },
        ),
    ]
