# Generated by Django 4.2.23 on 2025-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_bookcategory_moviecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='book_reviews/'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Movie poster image', null=True, upload_to='movie_reviews/'),
        ),
    ]
