# Generated by Django 4.2.23 on 2025-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_bookreview_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='en', help_text='Review language', max_length=2),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='en', help_text='Review language', max_length=2),
        ),
    ]
